{{- if and (not .Values.pulse.existingSecret) .Values.pulse.sealedSecret.encryptedPassword -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "tibber-pulse-bot.fullname" . }}
  {{- with .Values.pulse.sealedSecret.scope }}
  annotations:
    sealedsecrets.bitnami.com/{{ . }}: "true"
  {{- end }}
  labels:
    {{- include "tibber-pulse-bot.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "tibber-pulse-bot.fullname" . }}
      labels:
        {{- include "tibber-pulse-bot.labels" . | nindent 8 }}
    type: Opaque
  encryptedData:
    TIBBER_PULSE_PASSWORD: {{ .Values.pulse.sealedSecret.encryptedPassword | quote }}
{{- end -}}
