{{- if and (not .Values.pulse.existingSecret) (not .Values.pulse.sealedSecret.encryptedPassword) .Values.pulse.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tibber-pulse-bot.fullname" . }}
  labels:
    {{- include "tibber-pulse-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  TIBBER_PULSE_PASSWORD: {{ .Values.pulse.password | quote }}
{{- end -}}
